CV32E40Pv2 220 SIMD Builtins Version 1
openhwgroup/corev-gcc pull request #19
Opened 2023-01-31 14:57 UTC by NandniJamnadas

* `gcc/common/config/riscv/riscv-common.cc`: Added XCOREVSIMD
 extensions. Added riscv_xcorev_flags to SIMD extensions.
* gcc/config/riscv/riscv-opts.h: Added corresponding MASK and
  TARGET macros for XCOREVSIMD.
* `gcc/config/riscv/constraints.md`: Created a 6-bit signed immediate
  constraint "CV6".
* `gcc/config/riscv/corev-simd.def`: Defined 220 SIMD builtins with
  RISCV_BUILTIN.
* `gcc/config/riscv/corev-simd.md`: Machine description pattern for
  all 220 SIMD builtins.
* `gcc/config/riscv/predicates.md`: Created corresponding
  predicate for 6-bit signed immediate constraint "CV6".
* `gcc/config/riscv/riscv-builtins.cc: Created SIMD Avaliability
  Predicate, RISCV_FTYPE_NAME2, RISCV_FTYPE_ATYPES2. Added
  corresponding argument types for builtins.
* `gcc/config/riscv/riscv-ftypes.def`: Added corresponding
  DEF_RISCV_FTYPE return type and argument types for builtins.
* `gcc/config/riscv/riscv.md`: Added corresponding 220 UNSPEC macros
  and included "corev-simd.md"
* `gcc/testsuite/gcc.target/riscv/cv-simd-*`: 220 Compilation Tests and 1 MARCH test: `cv-simd-march-compile-1.c`.

2023-01-31 15:36 UTC, NandniJamnadas commented
GCC testing, RISC-V Target ONLY:

Category | Previous | With commit | Delta
-- | -- | -- | --
Expected passes | 3681 | 9630 | +5949
Unexpected failures | 53 | 53 | -
Unexpected successes | - | - | -
Expected failures | 6 | 6 | -
Unresolved testcases | 6 | 6 | -
Unsupported tests | 233 | 233 | -

2023-02-02 17:04 UTC, jeremybennett requested changes
This is an interim review, to capture various issues, which need addressing.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sci_b_si,        "cv_simd_add_sci_b",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
As discussed off line, all the `sci` variants are going to be replaced by patterns that automatically decide.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_h_si,            "cv_simd_add_h",            RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Shouldn't this (and `cv_simd_sub_h`) be of type `RISCV_USI_FTYPE_USI_USI_UQI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_h_si,          "cv_simd_dotup_h",          RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Do you want to insert a comment noting these are the SIMD dot product operations? Makes it easier to reference back to the specification.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sc_h_si,       "cv_simd_dotup_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UHI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sc_b_si,       "cv_simd_dotup_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UQI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotusp_sc_h_si,      "cv_simd_dotusp_sc_h",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_HI` (the reference is wrong, in this case the last argument is signed).

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotusp_sc_b_si,      "cv_simd_dotusp_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_QI` (the reference is wrong, in this case the last argument is signed).

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sci_b_si,      "cv_simd_dotup_sci_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
As noted earlier the `sci` versions need to go.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotsp_sc_h_si,       "cv_simd_dotsp_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_HI` (the reference is wrong, in this case the last argument is signed).

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotsp_sc_b_si,       "cv_simd_dotsp_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_QI` (the reference is wrong, in this case the last argument is signed).

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_h_si,         "cv_simd_sdotup_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Should the type be `RISCV_USI_FTYPE_USI_USI_USI`? Or is this because the final argument is also the destination argument?

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sc_h_si,      "cv_simd_sdotup_sc_h",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UHI_USI`, although the same questions applies as the the half word equivalent.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_b_si,         "cv_simd_sdotup_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Againt, should the type be `RISCV_USI_FTYPE_USI_USI_USI`? Or is this because the final argument is also the destination argument?

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sc_b_si,      "cv_simd_sdotup_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UQI_USI`, although the same questions apply as the the byte equivalent.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sci_h_si,     "cv_simd_sdotup_sci_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
Same comments as for the other dot production intrinsics apply for the rest of this section.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,        "cv_simd_extract_h",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
A comment before the bitmanip builtins would be useful. Also they should go above the dot products to match the reference documentation.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,        "cv_simd_extract_h",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
I think in all the following extract intrinsics the type should be `RISCV_USI_FTYPE_USI_UQI`, not `RISCV_USI_FTYPE_USI_QI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_insert_h_si,         "cv_simd_insert_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Shouldn't the insert builtins be of type `RISCV_USI_FTYPE_USI_USI_UQI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffle_sci_h_si,    "cv_simd_shuffle_sci_h",    RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
I think there is a mistake in the documentation, and this should be named `cv_simd_shuffle_sc_h` for consistency.  The same applies for the other `sci` shuffle instructions.  Also I think the type should be `RISCV_USI_FTYPE_USI_UQI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffleI0_sci_b_si,  "cv_simd_shuffleI0_sci_b",  RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
There is just one `cv_simd_shuffle_sc_b` function.  The two 2 bits of the constant final argument identify which opcode to generate.  I believe the type should be `RISCV_USI_FTYPE_USI_UQI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffle2_h_si,       "cv_simd_shuffle2_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Surely the `shuffle2` functions need type `RISCV_USI_FTYPE_USI_USI_USI`?

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_pack_b_si,           "cv_simd_pack_b",           RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
There is no `cv_simd_pack_b`. I think this should be `cv_simd_pack`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_packhi_b_si,         "cv_simd_packhi_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think this and the following instruction are of type `RISCV_USI_FTYPE_USI_USI_USI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpeq_sc_h_si,       "cv_simd_cmpeq_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_HI`  (similarly for the other signed half word scalar comparisons)

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpeq_sc_b_si,       "cv_simd_cmpeq_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_QI`  (similarly for the other signed byte scalar comparisons)

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpgtu_sc_h_si,      "cv_simd_cmpgtu_sc_h",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UHI`  (similarly for the other unsigned half word scalar comparisons)

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpgtu_sc_b_si,      "cv_simd_cmpgtu_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type should be `RISCV_USI_FTYPE_USI_UQI`  (similarly for the other unsigned byte scalar comparisons)

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_r_si,        "cv_simd_cplxmul_r",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Type should be `RISCV_USI_FTYPE_USI_USI_USI_UQI`, with the final argument used to control which/wether the `.div` variants of the instruction are generated.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_i_si,        "cv_simd_cplxmul_i",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Type should be `RISCV_USI_FTYPE_USI_USI_USI_UQI`, with the final argument used to control which/wether the `.div` variants of the instruction are generated.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_r_div2_si,   "cv_simd_cplxmul_r_div2",   RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
There are no `simd_cplxmul_?_div?` builtins. The `.div?` versions of instrructions are generate as appropriate by the `simd_cplxmul_?` builtin.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_div2_si,         "cv_simd_add_div2",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Home of the `cv_simd_add/sub_div` builtins are needed.  The relevant instructions are generated as needed by the `cv_simd_add_h` and `cv_simd_sub_h` builtins

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_subrotmj_si,         "cv_simd_subrotmj",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
This should be of type `RISCV_USI_FTYPE_USI_USI_UQI`, with the final constant argument used to determine whether to generate one of the `_div` variants.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_subrotmj_div2_si,    "cv_simd_subrotmj_div2",    RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
There are no `cv_simd_subrotmj_div?` builtins.

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sc_h_si,         "cv_simd_add_sc_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type shoudl be `RISCV_USI_FTYPE_USI_HI`

2023-02-02 17:04 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sc_b_si,         "cv_simd_add_sc_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
I think the type shoudl be `RISCV_USI_FTYPE_USI_QI`

2023-02-21 19:35 UTC, jeremybennett requested changes
Great piece of work.  There is a piece of technical cleanup needed to add in all the missing newlines at end of file. The other comment is a suggestion for the future.

With the missing newlines added, this will be good to merge.

2023-02-21 19:35 UTC, jeremybennett commented on gcc/config/riscv/riscv-ftypes.def
> +DEF_RISCV_FTYPE (4, (SI, SI, SI, SI, UQI))      //RISCV_SI_FTYPE_SI_SI_SI_UQI
Note warning about missing newline at end of file! Check other files as well (looks to be all tests!).

2023-02-21 19:35 UTC, jeremybennett commented on gcc/testsuite/gcc.target/riscv/cv-simd-subrotmj-div2-compile-1.c
> +/* { dg-do compile } */
I would be minded to merge all the subrotmj tests into one and have multiple scan-assembler lines at the end.  No need to change now, but would be a good cleanup later.

2023-02-21 20:15 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sci_b_si,        "cv_simd_add_sci_b",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
Resolved in the latest version

2023-02-21 20:17 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sci_b_si,        "cv_simd_add_sci_b",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
Resolved by newer commits.

2023-02-21 20:17 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_h_si,          "cv_simd_dotup_h",          RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:17 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_h_si,            "cv_simd_add_h",            RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:18 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sc_h_si,       "cv_simd_dotup_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:18 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sc_b_si,       "cv_simd_dotup_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:18 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_div2_si,         "cv_simd_add_div2",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:19 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_subrotmj_si,         "cv_simd_subrotmj",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:19 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_subrotmj_div2_si,    "cv_simd_subrotmj_div2",    RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:19 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sc_h_si,         "cv_simd_add_sc_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:19 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_sc_b_si,         "cv_simd_add_sc_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotusp_sc_b_si,      "cv_simd_dotusp_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotup_sci_b_si,      "cv_simd_dotup_sci_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotsp_sc_h_si,       "cv_simd_dotsp_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_dotsp_sc_b_si,       "cv_simd_dotsp_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_h_si,         "cv_simd_sdotup_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sc_h_si,      "cv_simd_sdotup_sc_h",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_b_si,         "cv_simd_sdotup_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sc_b_si,      "cv_simd_sdotup_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:20 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_sdotup_sci_h_si,     "cv_simd_sdotup_sci_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_SI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,        "cv_simd_extract_h",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,        "cv_simd_extract_h",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_insert_h_si,         "cv_simd_insert_h",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffle_sci_h_si,    "cv_simd_shuffle_sci_h",    RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffleI0_sci_b_si,  "cv_simd_shuffleI0_sci_b",  RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_shuffle2_h_si,       "cv_simd_shuffle2_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:21 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_pack_b_si,           "cv_simd_pack_b",           RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_packhi_b_si,         "cv_simd_packhi_b",         RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpeq_sc_h_si,       "cv_simd_cmpeq_sc_h",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpeq_sc_b_si,       "cv_simd_cmpeq_sc_b",       RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpgtu_sc_h_si,      "cv_simd_cmpgtu_sc_h",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cmpgtu_sc_b_si,      "cv_simd_cmpgtu_sc_b",      RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_r_si,        "cv_simd_cplxmul_r",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_i_si,        "cv_simd_cplxmul_i",        RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:22 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_cplxmul_r_div2_si,   "cv_simd_cplxmul_r_div2",   RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI, cvsimd),
Resolved by newer commits.

2023-02-21 20:24 UTC, jeremybennett requested changes

2023-02-21 20:24 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_h_si,			"cv_simd_add_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI_UQI, cvsimd),
Need to fix layout - possibly a tabbing issue?

2023-02-22 09:09 UTC, jeremybennett requested changes
Spotted a couple of type errors.

2023-02-22 09:09 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,		"cv_simd_extract_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
This should be `RISCV_SI_FTYPE_USI_QI` as per the documentation

2023-02-22 09:09 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_b_si,		"cv_simd_extract_b",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
This should be `RISCV_SI_FTYPE_USI_QI` as per the documentation

2023-02-22 12:36 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_h_si,		"cv_simd_extract_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
All fixed.

2023-02-22 12:36 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_extract_b_si,		"cv_simd_extract_b",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_QI, cvsimd),
All fixed

2023-02-22 12:37 UTC, jeremybennett commented on gcc/config/riscv/corev.def
> +RISCV_BUILTIN (cv_simd_add_h_si,			"cv_simd_add_h",     RISCV_BUILTIN_DIRECT, RISCV_USI_FTYPE_USI_USI_UQI, cvsimd),
Better, but still looks a bit odd in GitHub.  I suggest we leave this for a future cleanup.

2023-02-22 12:37 UTC, jeremybennett commented on gcc/config/riscv/riscv-ftypes.def
> +DEF_RISCV_FTYPE (4, (SI, SI, SI, SI, UQI))      //RISCV_SI_FTYPE_SI_SI_SI_UQI
All fixed.

2023-02-22 12:38 UTC, jeremybennett approved these changes
All issues now addressed.  Good to merge.

2023-02-22 13:41 UTC, merged